from Bio import Entrez, SeqIO
from collections import Counter

class DataFetcher:
    """
    Partially Generated by chatGPT
    """

    def __init__(self,gene_id):
        
        print("\nInitializing Object for Accessing Sequence Banks...\n")
        
        self.gene_id = gene_id
        self.record = None

    def fetch_sequence(self):
        """Fetch the gene sequence from GenBank."""
        Entrez.email = "nsawicki@umich.edu"  # Replace with your email
        handle = Entrez.efetch(db="nucleotide", id=self.gene_id, rettype="fasta", retmode="text")
        record = SeqIO.read(handle, "genbank")
        handle.close()
        return record

    def count_codons(self,sequence):
        """Count the codons in a given sequence."""
        codons = [str(sequence[i:i+3]) for i in range(0, len(sequence), 3)]
        codon_count = Counter(codons)
        return codon_count

    def run(self):

        self.record = self.fetch_sequence()
        print(self.record)
        print(self.record.seq)

        cds = None
        # Find the coding sequence (CDS)
        for feature in self.record.features:
            if feature.type == "CDS" and "gene" in feature.qualifiers:
                if "BRCA1" in feature.qualifiers["gene"]:
                    cds = feature.location.extract(record).seq
                    break

        # Analyze codon usage in the coding sequence
        #codon_count = self.count_codons(cds)

        # Get top 8 most common codons
        #top_codons = codon_count.most_common(8)
        #print("Top 8 codons in the BRCA1 coding sequence:", top_codons) 

        # Analyze codon usage in exons
        #exons = [feature for feature_tmp in record.features if feature.type == "exon"]
        #print(exons)
        #exon_sequence = "".join(str(record.seq[feature.location.start:feature.location.end]) for feature in exons)
        #codon_count = self.count_codons(exon_sequence)

        # Get top 8 most common codons
        #top_codons = codon_count.most_common(8)
        #print("Top 8 codons in the BRCA1 exons:", top_codons)

