from Bio import Entrez
from collections import Counter
Entrez.email = ""

class NucleotideQuery:

    """
    Partially Generated by chatGPT
    """
    def __init__(self, gene_id,db="nucleotide"):
        
        # Set your email here to inform NCBI who is requesting the data.
        self.db = db
        self.gene_id = gene_id

        self.sequence = ''

    def fetch_gene(self,print_full=False):
        
        # This method fetches <gene_id> information from the nucleotide database.
        try:
            handle = Entrez.efetch(db=self.db, id=self.gene_id, rettype="fasta", retmode="text")
            gene_data = handle.read()

            self.sequence = gene_data.split(' mRNA')[1].replace('\n','')
            if print_full:
                print(gene_data)

            return self.sequence

        except Exception as e:
            return str(e)

    def get_gene_id(self):
        return self.gene_id

    def get_sequence(self):
        return self.sequence

    def print_sequence(self):
        print(self.sequence)

    def count_codons(self):
        
        """Count the codons in a given sequence."""
        codons = [str(self.sequence[i:i+3]) for i in range(0, len(self.sequence), 3)]
        codon_count = Counter(codons)
        print(codon_count)

        return codon_count
